version: '3.2'

services:

  redis:
    image: redis:5.0.3
    restart: always
    volumes:
    - ./redis-data:/data
    command: redis-server --appendonly yes

  api:
    build: api
    restart: always
    depends_on:
    - "redis"

  bot:
    build: ./bot
    restart: always
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
    depends_on:
    - "redis"
    - "api"

  adminbot:
    build: ./adminbot
    restart: always
    environment:
      BOT_TOKEN: ${ADMINBOT_TOKEN}
    depends_on:
    - "redis"
    - "api"