version: '3.1'

services:

  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - "db"

  api:
    build: ./api
    ports:
      - 8080:5000
    environment:
      DATABASE_PASSWORD: example
    depends_on:
      - "db"

  bot:
    build: ./bot
    environment:
      BOT_TOKEN: '698374984:AAHt2v4CkCeJFomAzB0eJ7YQWCaDv5lFINw'
    depends_on:
      - "db"
      - "api"