version: '3.2'

services:

  db:
    image: postgres:alpine
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - "db"

  api:
    build: ./api
    restart: always
    ports:
      - 8080:5000
    environment:
      DATABASE_PASSWORD: example
    depends_on:
      - "db"

  bot:
    build: ./bot
    restart: always
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
    depends_on:
      - "db"
      - "api"