version: '3.2'

services:

#  db:
#    image: postgres:11-alpine
#    restart: always
#    volumes:
#      - ./postgres-data:/var/lib/postgresql/data
#    environment:
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  redis:
    image: redis:5.0.3
    restart: always
    volumes:
      - ./redis-data:/data
    command: redis-server --appendonly yes

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8081:8080

#  api-psql:
#    build: api-psql
#    restart: always
#    ports:
#      - 8080:5000
#    environment:
#      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
#    depends_on:
#      - "db"

  api:
    build: api
    restart: always
    ports:
    - 8080:5000
    depends_on:
    - "redis"

  bot:
    build: ./bot
    restart: always
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
    depends_on:
      - "redis"
      - "api"

  adminbot:
    build: ./adminbot
    restart: always
    environment:
      BOT_TOKEN: ${ADMINBOT_TOKEN}
    depends_on:
      - "redis"
      - "api"